FROM node:4-onbuild
# replace this with your application's default port
EXPOSE 8888

RUN npm install nodemon -g
RUN npm install -g requirejs
RUN npm install -g browserify

RUN npm install -g gulp
RUN npm install -g mocha