version: '3.5'

services:
  db:
    container_name: 'db_${PROJECT_NAME}_${ENV}'
    build:
      context: docker/db/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=db.${PROJECT_NAME}"
#      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.rule=Host:db.${PROJECT_NAME}.localhost"
#      - "traefik.frontend.passHostHeader=true"
#      - "traefik.port=1080"
      - "traefik.docker.network=traefik"

  php:
    container_name: 'php_${PROJECT_NAME}_${ENV}'
    build:
      context: docker/php/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
    volumes:
      - ./back/:/var/www/${PROJECT_NAME}/

  nginx:
    container_name: 'nginx_${PROJECT_NAME}_${ENV}'
    build:
      context: docker/nginx/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - php
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api.${PROJECT_NAME}"
#      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.rule=Host:api.${PROJECT_NAME}.localhost"
#      - "traefik.frontend.passHostHeader=true"
#      - "traefik.port=1080"
      - "traefik.docker.network=traefik"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back/public/:/var/www/${PROJECT_NAME}/

  node:
    container_name: 'node_${PROJECT_NAME}_${ENV}'
    build:
      context: docker/node/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=node.${PROJECT_NAME}"
#      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.frontend.rule=Host:node.${PROJECT_NAME}.localhost"
#      - "traefik.frontend.passHostHeader=true"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik"
    volumes:
      - ./front/:/var/www/${PROJECT_NAME}/

networks:
  default:
    name: network_${PROJECT_NAME}_${ENV}
  traefik:
    external: true