version: '3.7'

services:
    nginx:
        container_name: apiplatform_boilerplate_nginx
        image: nginx:latest
        env_file: ./.env
        volumes:
            - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            # - ./web/:/app/
            - ./:/opt/project/
            - ./var/log/nginx/:/var/log/nginx/
        networks:
            - apiplatform_boilerplate
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=apiplatform_boilerplate"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.rule=Host:apiplatform_boilerplate.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.port=80"
            - "traefik.docker.network=traefik"
        depends_on:
            - php
        ports:
            - 8002:80

    php:
        container_name: apiplatform_boilerplate_php
        build:
            context: ./docker/php/
        depends_on:
            - database
        env_file: ./.env
        volumes:
            - ./:/opt/project/
            # - ./docker/php/ini/:/usr/local/etc/php/
        environment:
            - SYMFONY_ENV=${SYMFONY_ENV}
            - MYSQL_PORT=${DATABASE_PORT}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        networks:
          - apiplatform_boilerplate

    database:
        container_name: apiplatform_boilerplate_database
        image: mariadb:10.4.4-bionic
        # image: mariadb:10.1.21
#        volumes:
#            - ./docker/database/data:/var/lib/mysql
            # marche pas sous windows en NTFS
        env_file: ./.env
        environment:
            - MYSQL_PORT=${DATABASE_PORT}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        networks:
          - apiplatform_boilerplate
        ports:
            - 33006:3306

    phpmyadmin:
        container_name: apiplatform_boilerplate_phpmyadmin
        image: phpmyadmin/phpmyadmin
        env_file: ./.env
        links:
            - database
        environment:
            - PMA_HOST=${DATABASE_HOST}
        networks:
            - apiplatform_boilerplate
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=pma.apiplatform_boilerplate"
            - "traefik.backend.loadbalancer.method=drr"
            - "traefik.frontend.rule=Host:pma.apiplatform_boilerplate.localhost"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.docker.network=traefik"

networks:
    apiplatform_boilerplate:
        name: apiplatform_boilerplate
    traefik:
        external: true